const products=[
{name:'FLEXROTOR',type:'UAV',maker:'Airbus',desc:'Expeditionary VTOL ISR system.',specs:['Endurance 12–14 h','VTOL','EO/IR','Portable GCS']},
{name:'RAYBIRD ACS-3',type:'UAV',maker:'Skyeton',desc:'Long-endurance tactical ISR platform.',specs:['Endurance 28+ h','Fixed-wing','EO/IR','SATCOM option']},
{name:'SDO 50',type:'UAV',maker:'SwissDrones',desc:'Heavy-lift unmanned helicopter.',specs:['Endurance 3 h','VTOL','Heavy payload','Maritime capable']},
{name:'MQ-9B SkyGuardian',type:'UAV',maker:'General Atomics',desc:'MALE remotely piloted aircraft.',specs:['Endurance 40+ h','40,000+ ft','Multi-sensor','SATCOM']},
{name:'Ghost-X',type:'UAV',maker:'Anduril',desc:'Modular expeditionary reconnaissance UAV.',specs:['Tactical ISR','Modular payload','Autonomous','Lattice enabled']},
{name:'Universal Portable GCS',type:'GCS',maker:'KRIN Concept',desc:'Portable universal ground control station.',specs:['Ruggedized','Multi-UAV','Live video','Mission planning']},
{name:'EO/IR Turret',type:'Payload',maker:'Multiple',desc:'Stabilized day/night ISR payload.',specs:['EO camera','MWIR/LWIR','Laser rangefinder','Tracking']},
{name:'Tactical Data Link',type:'Data Link',maker:'Multiple',desc:'Encrypted line-of-sight communications.',specs:['AES-256','Video + telemetry','Portable','Mesh capable']}
];
let projects=[
{name:'KAT Drone Integration',contract:'KG-2026-001',value:25000000,organization:'Army',progress:65,priority:'High',status:'Active',endDate:'2026-07-22'},
{name:'Naval ISR Platform',contract:'KG-2026-002',value:42500000,organization:'Navy',progress:35,priority:'Medium',status:'Planning',endDate:'2026-08-15'},
{name:'Air Force Sensor Upgrade',contract:'KG-2026-003',value:18700000,organization:'Air Force',progress:45,priority:'High',status:'Active',endDate:'2026-07-30'},
{name:'Border Surveillance Trial',contract:'KG-2026-004',value:12400000,organization:'Police',progress:80,priority:'Medium',status:'Active',endDate:'2026-07-18'}
];
const customers=[['Royal Thai Army','Army','Project Coordination Office'],['Royal Thai Navy','Navy','Naval Aviation Division'],['Royal Thai Air Force','Air Force','Operations & Technology'],['Private Aviation Partner','Private','Program Management']];
const views=document.querySelectorAll('.view'),navs=document.querySelectorAll('.nav');
function showView(id){views.forEach(v=>v.classList.toggle('active',v.id===id));navs.forEach(n=>n.classList.toggle('active',n.dataset.view===id));document.getElementById('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
navs.forEach(n=>n.onclick=()=>showView(n.dataset.view));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{showView(b.dataset.jump);if(b.dataset.category){document.getElementById('productCategory').value=b.dataset.category;renderProducts()}});document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'THB',maximumFractionDigits:0}).format(v);
function renderProjects(){const q=(document.getElementById('projectSearch')?.value||'').toLowerCase(),org=document.getElementById('orgFilter')?.value||'',st=document.getElementById('statusFilter')?.value||'',pr=document.getElementById('priorityFilter')?.value||'';const filtered=projects.filter(p=>(!q||p.name.toLowerCase().includes(q)||p.contract.toLowerCase().includes(q))&&(!org||p.organization===org)&&(!st||p.status===st)&&(!pr||p.priority===pr));document.getElementById('priorityProjects').innerHTML=filtered.slice(0,4).map(p=>`<div class="project-row"><div class="project-top"><div><b>${p.name}</b><div class="meta"><span>${p.contract}</span><span>${p.organization}</span><span>${money(p.value)}</span></div></div><span class="badge ${p.priority}">${p.priority}</span></div><div class="progress"><span style="width:${p.progress}%"></span></div><div class="meta"><span>${p.progress}% complete</span><span>${p.status}</span><span>Due ${p.endDate}</span></div></div>`).join('')||'<p>No matching projects.</p>';document.getElementById('projectTable').innerHTML=projects.filter(p=>!q||p.name.toLowerCase().includes(q)||p.contract.toLowerCase().includes(q)).map(p=>`<tr><td><b>${p.name}</b></td><td>${p.contract}</td><td>${money(p.value)}</td><td>${p.organization}</td><td><div class="progress"><span style="width:${p.progress}%"></span></div><small>${p.progress}%</small></td><td><span class="badge ${p.priority}">${p.priority}</span></td><td>${p.status}</td></tr>`).join('');document.getElementById('totalProjects').textContent=projects.length}
['projectSearch','orgFilter','statusFilter','priorityFilter'].forEach(id=>document.getElementById(id)?.addEventListener('input',renderProjects));document.getElementById('clearDashboard').onclick=()=>{['orgFilter','statusFilter','priorityFilter'].forEach(id=>document.getElementById(id).value='');renderProjects()};
function renderProducts(){const q=document.getElementById('productSearch').value.toLowerCase(),cat=document.getElementById('productCategory').value,m=document.getElementById('makerFilter').value;const list=products.filter(p=>(!q||p.name.toLowerCase().includes(q)||p.desc.toLowerCase().includes(q))&&(!cat||p.type===cat)&&(!m||p.maker===m));document.getElementById('productGrid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-type">${p.type} • ${p.maker}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="specs">${p.specs.map(s=>`<span>${s}</span>`).join('')}</div><button>View details</button></article>`).join('')||'<p>No products found.</p>'}
['productSearch','productCategory','makerFilter'].forEach(id=>document.getElementById(id).addEventListener('input',renderProducts));document.getElementById('clearProducts').onclick=()=>{['productSearch','productCategory','makerFilter'].forEach(id=>document.getElementById(id).value='');renderProducts()};document.getElementById('customerGrid').innerHTML=customers.map(c=>`<article class="customer-card"><div class="avatar">${c[0].split(' ').map(x=>x[0]).slice(0,2).join('')}</div><h3>${c[0]}</h3><p>${c[1]}</p><small>${c[2]}</small><br><br><button>View profile</button></article>`).join('');
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.open).classList.add('open'));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));document.getElementById('projectModal').onclick=e=>{if(e.target.id==='projectModal')e.currentTarget.classList.remove('open')};document.getElementById('projectForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);projects.unshift({name:f.get('name'),contract:f.get('contract'),value:Number(f.get('value')),organization:f.get('organization'),priority:f.get('priority'),status:f.get('status'),progress:Number(f.get('progress')),endDate:f.get('endDate')||'TBD'});e.currentTarget.reset();document.getElementById('projectModal').classList.remove('open');renderProjects();showView('projects')};
document.getElementById('exportCsv').onclick=()=>{const rows=[['Project','Contract','Value','Organization','Progress','Priority','Status'],...projects.map(p=>[p.name,p.contract,p.value,p.organization,p.progress,p.priority,p.status])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='kat-projects.csv';a.click()};
let calDate=new Date(2026,6,1);const holidays={'2026-01-01':"New Year's Day",'2026-04-06':'Chakri Memorial Day','2026-04-13':'Songkran','2026-04-14':'Songkran','2026-04-15':'Songkran','2026-05-01':'Labour Day','2026-05-04':'Coronation Day','2026-06-03':"Queen Suthida's Birthday",'2026-07-28':"King's Birthday",'2026-08-12':"Mother's Day",'2026-10-13':'King Bhumibol Memorial Day','2026-10-23':'Chulalongkorn Day','2026-12-05':"Father's Day",'2026-12-10':'Constitution Day','2026-12-31':"New Year's Eve"};const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;function renderCalendar(){const y=calDate.getFullYear(),m=calDate.getMonth();document.getElementById('calendarTitle').textContent=calDate.toLocaleString('en-US',{month:'long',year:'numeric'});const start=new Date(y,m,1).getDay(),arr=[];for(let i=0;i<42;i++){const d=new Date(y,m,1-start+i),k=key(d),cls=['day'];if(d.getMonth()!==m)cls.push('muted');if(k===key(new Date()))cls.push('today');if(holidays[k])cls.push('holiday');arr.push(`<div class="${cls.join(' ')}" title="${holidays[k]||''}">${d.getDate()}</div>`)}document.getElementById('calendar').innerHTML=arr.join('');const hs=Object.entries(holidays).filter(([k])=>{const d=new Date(k+'T00:00:00');return d.getMonth()===m&&d.getFullYear()===y});document.getElementById('holidayNote').innerHTML=hs.length?`<b>Thai holidays:</b> ${hs.map(([k,v])=>`${new Date(k+'T00:00:00').getDate()} ${v}`).join(' • ')}`:'No public holidays this month.'}
document.getElementById('prevMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar()};document.getElementById('nextMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar()};document.getElementById('todayMonth').onclick=()=>{calDate=new Date();renderCalendar()};document.getElementById('globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){showView('products');document.getElementById('productSearch').value=e.target.value;renderProducts()}});document.getElementById('addProduct').onclick=()=>alert('Front-end prototype: connect this action to Flask/PostgreSQL for permanent product records.');renderProjects();renderProducts();renderCalendar();
